spring.application.name=practicaSpringBoot
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

management.endpoints.web.exposure.exclude=health

spring.security.user.name=jhonatan
spring.security.user.password=12345

info.app.name=Mi super apliacion
info.app.descripcion=App de practica SpringBoot
info.app.version=1.0.0